# fly.toml app configuration file generated for bkhack-wispy-wildflower-6115 on 2026-05-25T03:31:03+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bkhack-wispy-wildflower-6115'
primary_region = 'sin'

[build]
  builder = 'heroku/buildpacks:20'
  buildpacks = ['https://cnb-shim.herokuapp.com/v1/hashnuke/elixir']

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
	grace_period = "100s"
	interval = "300s"
	method = "GET"
	timeout = "50s"
	path = "/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
