#!/usr/bin/python
import contextlib

@contextlib.contextmanager
def tmpdir_open(root, name=None):
  import uuid, os
  dirname = f"{root}/{"" if name is None else (name + "-")}{uuid.uuid4()}"
  os.mkdir(dirname)
  yield dirname

@contextlib.contextmanager
def tmpfile_open(dir):
  import uuid, os
  filename = f"{dir}/{uuid.uuid4()}"
  yield filename
  # os.unlink(filename)

def replaces(target, ls):
  ret = target
  for (pat, replace) in ls:
    ret = target.replace(pat, replace)
  return ret

if __name__ == "__main__":
  import argparse, os.path
  args = argparse.ArgumentParser(prog="typst compile")
  args.add_argument("filename")
  args.add_argument("-r", "--root", nargs='?')
  args.add_argument("--package-path", nargs='?')
  args.add_argument("output")
  args = args.parse_args()
  with open(args.filename, "r") as f: file_content = f.read()
  file_content = replaces(file_content, [
    ("\\\n  ", "\n\n"),
    ("\n-", "-"), ("\n--", "--"),
    ("\n;", ";"), ("\n:", ":"),
    ("\n,", ","), ("\n.", ".")
  ])
  file_content = '#import "/article"\n#show: article.doc\n' + file_content
  with tmpfile_open(os.path.dirname(args.filename)) as input:
    with open(input, "w+") as f: f.write(file_content)
    command = []
    command += ["typst", "compile"]
    command += ["--root", args.root] if args.root is not None else []
    command += ["--package-path", args.package_path] if args.package_path is not None else []
    command += [input, args.output]
    import subprocess
    proc = subprocess.run(command)
  exit(proc.returncode)
