#!/usr/bin/python
import os.path
import tempfile
import argparse
import subprocess
import time
import contextlib

@contextlib.contextmanager
def tmpdir_open(root, name=None):
  import uuid
  import os
  dirname = f"{root}/{"" if name is None else (name + "-")}{uuid.uuid4()}"
  os.mkdir(dirname)
  yield dirname

@contextlib.contextmanager
def tmpfile_open(dir):
  import uuid
  import os
  filename = f"{dir}/{uuid.uuid4()}"
  yield filename
  os.unlink(filename)

if __name__ == "__main__":
  args = argparse.ArgumentParser(prog="typst-compile")
  args.add_argument("filename")
  args.add_argument("-r", "--root", nargs='?')
  args.add_argument("output")
  args = args.parse_args()
  with open(args.filename, "r") as f:
    file_content = f.read()
  file_content = file_content.replace("\\\n  ", "\n\n")
  file_content = file_content.replace("\n--", "--")
  file_content = file_content.replace("\n-", "-")
  file_content = file_content.replace("\n;", ";")
  file_content = file_content.replace("\n:", ":")
  file_content = file_content.replace("\n,", ",")
  file_content = file_content.replace("\n.", ".")
  file_content = '#import "/article": *\n#show: doc\n' + file_content
  with tmpfile_open(os.path.dirname(args.filename)) as input:
    with open(input, "w+") as f:
      f.write(file_content)
    command = []
    command += ["typst", "compile"]
    command += ["--root", args.root] if args.root is not None else []
    command += [input, args.output]
    proc = subprocess.run(command)
  exit(proc.returncode)
