(rule
 (target dist-storybook)
 (deps (source_tree .) .storybook (alias react-storybook))
 (action (bash "pnpm storybook build --config-dir ${PWD}/.storybook --output-dir ${PWD}/dist-storybook >&2")))

(melange.emit
 (target output)
 (alias react-storybook)
 (libraries reason-react bkhack)
 (preprocess
  ; The `pps` field is a list of ppx to apply to the sources before generating JavaScript. melange.ppx allows to use Melange attributes [@mel. ...] (https://melange.re/v2.0.0/communicate-with-javascript/#attributes)
  ; reason-react-ppx allows to use JSX for ReasonReact components by using the [@JSX] attributes from Reason: https://reasonml.github.io/docs/en/jsx
  (pps melange.ppx reason-react-ppx))
 (module_systems es6))

(rule
 (target .storybook)
 (deps (source_tree %{project_root}/build_aux/storybook))
 (action (run cp -r %{project_root}/build_aux/storybook .storybook)))

