(rule
 (mode promote)
 (target (dir _output))
 (deps (:entries (glob_files Page__*.typ)) (glob_files *) article)
 (action (progn
  (run mkdir %{target})
  (run %{dep:app.exe} typst compile --article-at-root=true --output=%{target} --package-path=%{dep:_packages} %{entries})
 )))

(rule
 (target article)
 (deps %{project_root}/article (:typc-article %{project_root}/src_vendors/opt-utopk/u/article))
 (action (copy %{typc-article} article))
)

(rule
 (target (dir _packages))
 (deps %{project_root}/src/Diagramming/dist)
 (action (progn
  (run mkdir -p _packages/local/diagramming)
  (concurrent (run cp -r %{project_root}/src/Diagramming/dist/. _packages/local/diagramming/0.1.0))
 ))
)

(executable
 (name app)
 (libraries eio eio_main cmdliner re typst_compile))
