(library
 (libraries ppxlib ppx_comptime__topcore__evalproc ppx_comptime__topcore__module_name ppx_comptime__topcore__unparse re sexplib)
 (preprocess (pps ppxlib.metaquot))
 (modules Ppx_comptime_core)
 (name ppx_comptime_core))

(library
 (kind ppx_rewriter)
 (libraries ppxlib ppx_comptime_core)
 (modules Ppx_comptime)
 (name ppx_comptime))

(executable
 (libraries ppxlib ppx_comptime_core)
 (preprocess (pps ppxlib.metaquot))
 (modules Pp_comptime)
 (name pp_comptime))

