(rule
 (alias all)
 (deps dist firebase.json)
 (action (bash "\"$(pnpm root)\"/.bin/firebase deploy")))

(copy_files (files %{project_root}/build_aux/firebase.json))

(rule
 (alias bundle)
 (targets dist (dir distserve))
 (deps (:serve (alias Service/default))
       (:web distweb)
       (:static (source_tree Static))
       (:devbook Devbook/_output)
       (:doc %{project_root}/src/Doc/dist))
 (action (concurrent
  (progn (run mkdir -p dist)
         (bash "cd %{project_root} && cp -sr ${PWD}/src/distweb/. src/dist"))
  (progn (run mkdir -p dist/doc)
         (bash "cd %{project_root} && cp -sr ${PWD}/src/Doc/dist/. src/dist/doc"))
  (progn (run mkdir -p distserve)
         (bash "cd %{project_root} && cp -sr ${PWD}/src/Service/. src/distserve"))
  (progn (run mkdir -p dist)
         (bash "cd %{project_root} && cp -sr ${PWD}/src/Static/. src/dist"))
  (progn (run mkdir -p dist/devbook)
         (bash "cd %{project_root} && cp -sr ${PWD}/src/Devbook/_output/. src/dist/devbook"))
 ))
)

(rule
 (targets distweb)
 (deps (:static-lucide node_modules__lucide-static)
       (:src (alias react)))
 (action
  (run %{dep:webpackgen.exe}
   --css_only=%{env:CSS_ONLY=false}
   --verbose=false --optimization=%{profile} --output=%{targets} --src_dir=./ --target_dir=output/
   --generative_dir=%{dep:generative} --lucide_dir=node_modules__lucide-static/))
)

(rule
 (target node_modules__lucide-static)
 (action (bash "cp -L -r \"$(pnpm root)\"/lucide-static node_modules__lucide-static")))

(data_only_dirs Static)

(rule
 (target Fiberlet__src__Test_timer__re__p'.ml)
 (deps Test_timer.re.pp.ml)
 (action (run cp -s /tmp/%{target} %{target})))

(rule
 (target Fiberlet__src__Test_timer__re__q'.ml)
 (deps Test_timer.re.pp.ml)
 (action (run cp -s /tmp/%{target} %{target})))

(rule
 (targets (dir generative))
 (deps Page__app.re.pp.ml)
 (action (progn
  (run mkdir -p generative)
  (concurrent
   (run cp -s /tmp/generative/src__Page__app__re__HintPanel__feed__hint.css generative/src__Page__app__re__HintPanel__feed__hint.css)
  )
 )))

; `melange.emit` is a Dune stanza that will produce build rules to generate
; JavaScript files from sources using the Melange compiler
; https://dune.readthedocs.io/en/stable/melange.html#melange-emit
; Deploy [bkhack] right here.
(melange.emit

 ; The `target` field is used by Dune to put all JavaScript artifacts in a specific folder inside `_build/default`
 ; This field `target` allows to have multiple `melange.emit` stanzas in the `dune` file
 ; if, for example, we want to produce ES6 and CommonJS output from the same sources.
 (target output)

 ; The `alias` field can be used later on to build just the artifacts from this `melange.emit`
 ; by calling `dune build @react`.
 ; Note that if no `alias` field is defined, a default `melange` alias will be used instead.
 (alias react)

 ; Here's the list of dependencies of the stanza. In this case (being `melange.emit`),
 ; Dune will look into those dependencies and generate rules with JavaScript targets
 ; for the modules in those libraries as well.
 ; Caveat: the libraries need to be specified with `(modes melange)`.
 (libraries bkhack)

 (modules )

 ; Uncomment the following to copy the generated JavaScript files inside the source tree
 ; (promote (until-clean))

 ; module_systems is a list of module systems to generate code for (es6, commonjs)
 ; Change to (module_systems es6 commonjs) if you want to generate both
 ; https://melange.re/v2.0.0/build-system/#commonjs-or-es6-modules
 (module_systems es6))

(alias
 (name react)
 (deps (package bkhack-compiler) Devbook/_output (glob_files dune-compiler)))

(library
 (kind ppx_rewriter)
 (name ppxfiber)
 (modules Fiber__ppx)
 (libraries ppxlib ppx_comptime__topcore__unparse containers)
 (preprocess (pps ppxlib.metaquot)))

; `bkhack` is an abstract, implicitly heterogeneous full-stack application,
; where it is usable first as a web front-end and whose back-end is pluggable. 
(library
 ; Name of library, and is name of package
 (name bkhack) (public_name bkhack)
 ; Dependencies of the stanza.
 (libraries reason-react melange-json melange__containers quel melange-fetch
            cprg melange__cmarkit melange__iter melange__re melange.belt)
 (modules :standard \ Fiber__ppx Webpackgen Webpackgen2 Webpackgen2__comm Css_gen Build Kernel Dune_typst Ppx_comptime Ppx_comptime_core Pp_comptime Gen)
 (preprocess
  ; The `pps` field is a list of ppx to apply to the sources before generating JavaScript. melange.ppx allows to use Melange attributes [@mel. ...] (https://melange.re/v2.0.0/communicate-with-javascript/#attributes)
  ; reason-react-ppx allows to use JSX for ReasonReact components by using the [@JSX] attributes from Reason: https://reasonml.github.io/docs/en/jsx
  (pps melange.ppx reason-react-ppx ppx_comptime ppxfiber))
 (modes melange))

(subdir Shell+comptime
 (copy_files (files ../{Shellgen,Shell__sym}.re))
 (library
  (name shell__comptime) (public_name bkhack-compiler.shell)
  (libraries containers)
  (modes byte)
  (wrapped false)))

(executable
 (libraries eio eio_main buildlib
            cmdliner re containers webpackgen2__comm)
 (modules webpackgen)
 (name webpackgen))

(library
 (name webpackgen2__comm)
 (modules Webpackgen2__comm)
 (libraries eio jsont bytesrw jsont.bytesrw containers))

(executable
 (libraries eio eio_main buildlib
            cmdliner re containers webpackgen2__daemon)
 (modules webpackgen2)
 (name webpackgen2))

(library
 (libraries eio containers re)
 (flags -open Containers.Fun)
 (modules Build)
 (name buildlib))

(library
 (modes byte)
 (libraries containers re)
 (modules Css_gen Kernel)
 (public_name bkhack-compiler.css_gen)
 (flags -open Containers.Fun)
 (name css_gen))

(executable
 (name dune_typst)
 (modules Dune_typst)
 (libraries eio eio_main cmdliner sexplib containers toml)
 (flags -open Containers.Fun))

(library
 (libraries ppxlib ppx_comptime__topcore__evalproc ppx_comptime__topcore__module_name ppx_comptime__topcore__unparse re sexplib)
 (preprocess (pps ppxlib.metaquot))
 (modules Ppx_comptime_core)
 (name ppx_comptime_core))

(library
 (kind ppx_rewriter)
 (libraries ppxlib ppx_comptime_core)
 (modules Ppx_comptime)
 (name ppx_comptime))

(executable
 (libraries ppxlib ppx_comptime_core)
 (preprocess (pps ppxlib.metaquot))
 (modules Pp_comptime)
 (name pp_comptime))

