(rule
 (alias bundle)
 (targets dist distserve)
 (deps (:bundle webpackgen.exe)
       (:src (alias react))
       (:static (source_tree Static))
       (:serve (alias Service/default))
       (:static-lucide node_modules__lucide-static))
 (action (concurrent
  (run %{bundle}
   --verbose=false --optimization=%{profile} --output=dist --src_dir=./ --target=output
    :static %{static} --generative_dir=%{dep:generative}
   --lucide_dir=node_modules__lucide-static/)
  (run cp -r Service distserve)
 )))

(rule
 (target node_modules__lucide-static)
 (action (bash "cp -L -r \"$(pnpm root)\"/lucide-static node_modules__lucide-static")))

(data_only_dirs Static)

(dynamic_include ../services)

(rule
 (target generative)
 (deps (alias react))
 (action (progn
  (run mkdir -p generative)
  (run cp -r /tmp/generative .)
 )))

; `melange.emit` is a Dune stanza that will produce build rules to generate
; JavaScript files from sources using the Melange compiler
; https://dune.readthedocs.io/en/stable/melange.html#melange-emit
; Deploy [bkhack] right here.
(melange.emit

 ; The `target` field is used by Dune to put all JavaScript artifacts in a specific folder inside `_build/default`
 ; This field `target` allows to have multiple `melange.emit` stanzas in the `dune` file
 ; if, for example, we want to produce ES6 and CommonJS output from the same sources.
 (target output)

 ; The `alias` field can be used later on to build just the artifacts from this `melange.emit`
 ; by calling `dune build @react`.
 ; Note that if no `alias` field is defined, a default `melange` alias will be used instead.
 (alias react)

 ; Here's the list of dependencies of the stanza. In this case (being `melange.emit`),
 ; Dune will look into those dependencies and generate rules with JavaScript targets
 ; for the modules in those libraries as well.
 ; Caveat: the libraries need to be specified with `(modes melange)`.
 (libraries bkhack)

 (modules )

 ; Uncomment the following to copy the generated JavaScript files inside the source tree
 ; (promote (until-clean))

 ; module_systems is a list of module systems to generate code for (es6, commonjs)
 ; Change to (module_systems es6 commonjs) if you want to generate both
 ; https://melange.re/v2.0.0/build-system/#commonjs-or-es6-modules
 (module_systems es6))

(alias
 (name react)
 (deps (package bkhack-compiler)))

(library
 (kind ppx_rewriter)
 (name ppxfiber)
 (modules Fiber__ppx)
 (libraries ppxlib ppx_comptime__topcore__unparse containers)
 (preprocess (pps ppxlib.metaquot)))

; `bkhack` is an abstract, implicitly heterogeneous full-stack application,
; where it is usable first as a web front-end and whose back-end is pluggable. 
(library
 ; Name of library, and is name of package
 (name bkhack) (public_name bkhack)
 ; Dependencies of the stanza.
 (libraries reason-react melange-json melange__containers quel bkhack__experimental
            cprg melange__cmarkit melange__iter melange__re melange.belt)
 (modules :standard \ Fiber__ppx Webpackgen Css_gen build kernel)
 (flags -w -32)
 (preprocess
  ; The `pps` field is a list of ppx to apply to the sources before generating JavaScript. melange.ppx allows to use Melange attributes [@mel. ...] (https://melange.re/v2.0.0/communicate-with-javascript/#attributes)
  ; reason-react-ppx allows to use JSX for ReasonReact components by using the [@JSX] attributes from Reason: https://reasonml.github.io/docs/en/jsx
  (pps melange.ppx reason-react-ppx ppx_comptime ppxfiber))
 (modes melange))

(subdir Shell+comptime
 (copy_files (files ../{Shellgen,Shell__sym}.re))
 (library
  (name shell__comptime) (public_name bkhack-compiler.shell)
  (libraries containers)
  (modes byte)
  (wrapped false)))

(executable
 (libraries eio eio_main buildlib
            cmdliner re containers)
 (modules webpackgen)
 (name webpackgen))

(library
 (libraries eio containers re)
 (flags -open Containers.Fun)
 (modules build)
 (name buildlib))

(library
 (modes byte)
 (libraries containers re)
 (modules Css_gen kernel)
 (public_name bkhack-compiler.css_gen)
 (flags -open Containers.Fun)
 (name css_gen))

(subdir Diagramming
 (copy_files (files ../Diagramming*))
 (rule (target typst.toml)
  (action (run mv %{dep:Diagramming__typst.toml} typst.toml)))
 (rule (target lib.typ)
  (action (run mv %{dep:Diagramming.typ} lib.typ)))
)
